"""add table heroes column fk team_id

Revision ID: 4cf379732796
Revises: 41d7317229e3
Create Date: 2023-08-19 15:11:11.762476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4cf379732796"
down_revision: Union[str, None] = "41d7317229e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("heroes", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "heroes", "teams", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "heroes", type_="foreignkey")
    op.drop_column("heroes", "team_id")
    # ### end Alembic commands ###
